### ISSUE TITLE
Not compatible with pry 0.12

### ISSUE THREAD

**Issue by RobinDaugherty** [seikichi/pry-inline#8]
The current release of `pry-inline` does not work with `pry` 0.12, at least according to the gemspec. At this time, upgrading `pry` downgrades `pry-inline` to 0.1.0, since that release had a less-restrictive version specifier for `pry`.

**Comment by seikichi** [comment]
Thank you for reporting this issue. I'll fix ASAP.

**Comment by seikichi** [comment]
Thanks @RobinDaugherty 

I released v1.0.5 ( https://rubygems.org/gems/pry-inline/versions/1.0.5 ), which works with pry 0.12.
